Adnan/groot 142 new embrace email template preview modal
bank-green/nuxt-bank-green pull request #126
Opened 2024-03-31 18:25 UTC by AdnanHarami

I've implemented the new layout design for the contact form. Once approved, I'll proceed with integrating this form into the UK banks.

2024-04-05 02:49 UTC, PooriaT requested changes

2024-04-05 16:55 UTC, RogerTangos commented on components/EmbraceModal.vue
Regarding font, I'm happy for it look good, but don't have a preference for how. Questions like these should go to the designers

2024-04-07 22:24 UTC, AdnanHarami reviewed
Hey @PooriaT , I believe now it should be fixed , also clicking "cancel" does not destroy the form information now and I've added a cursor pointer to the back button

2024-04-08 01:46 UTC, PooriaT approved these changes
Thanks @AdnanHarami

2024-04-08 13:22 UTC, merged