Migrate all bank specific content to use DBG
bank-green/nuxt-bank-green pull request #190
Opened 2024-10-20 17:04 UTC by AlBillington

Remove all references to prismic bankPages. DBG should be the source of truth for all bank specific data
prismic to DBG field mappings:

Bankpage
headline -> 'header',
subtitle -> 'subtitle',
description1 -> 'summary',
description2 ->'details',
description3 ->'fromTheWebsite'
SFIpage
ourTake -> ourTake

I have updated the DBG fields so they all have the same values as prismic

Simplified the 6 very similar bank components into one

2024-10-21 14:03 UTC, RogerTangos requested changes
Before merging this, please edit DBG to use the same field names as prismic and then reconfigure this PR to use those naming conventions

2024-10-27 23:11 UTC, AlBillington commented
renamed fields on DBG and updated here

2024-10-29 14:30 UTC, RogerTangos requested changes
Two issues here:

1. The default text will still need to be editable in prismic. It might be worth updating the slice names there in a separate PR.

2. Our Take isn't showing up in the wizard. If this PR is merged, it won't be editable at all. It needs to be either added to the wizard or taken out of teh PR in order for the PR to be approved.

2024-10-30 04:42 UTC, AlBillington commented on pages/sustainable-eco-banks/[bankTag].vue
> +      :our-take="details?.ourTake"
I added it to retool, I already migrated the existing data as well from prismic to DBG

2024-10-30 04:44 UTC, AlBillington commented on utils/banks.js
> +export function getDefaultFields(rating, bankname) {
I updated this code to pull from prismic again

2024-10-31 13:47 UTC, RogerTangos requested changes
It looks like there are some text formatting issues on the bank pages. It may be helpful to run through the checklist [here](https://app.nuclino.com/BankGreen/How-To-Guides/-How-to-manually-check-that-the-BankGreen-website-is-working-817c5d5c-e108-4971-b455-5defabf16c87)

2024-10-31 14:02 UTC, RogerTangos commented
<img width="1625" alt="Screenshot 2024-10-31 at 14 46 51" src="https://github.com/user-attachments/assets/8b6405b3-7877-4ddc-a1ac-3fe4d9a4488f">
<img width="1106" alt="Screenshot 2024-10-31 at 14 48 20" src="https://github.com/user-attachments/assets/0bed27b9-5f00-48fb-831a-62c7adb3c67c">

http://localhost:3000/banks/beneficial_state_bank
http://localhost:3000/banks/allica_bank
http://localhost:3000/banks/habito
http://localhost:3000/banks/abn_amro
https://test.bank.green/banks/jpmorgan_chase

2024-10-31 14:29 UTC, RogerTangos commented
Oh man. These pages have been simplified and unsimplified a few times. My opinion is generally in line with whichever developer happens to be doing the work. For now, simplified is probably better. :P

2024-11-01 03:28 UTC, AlBillington commented
haha, I definitely always lean toward simpler code and fewer different systems.  I fixed the issues you flagged and tested the examples

2024-11-04 16:32 UTC, merged